# Generated by Django 4.2.5 on 2023-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_nike', '0004_advertising'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertising',
        ),
        migrations.AddField(
            model_name='sneakers',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
