# Generated by Django 4.2.5 on 2023-09-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_nike', '0005_delete_advertising_sneakers_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='akciya',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='price_type',
            field=models.CharField(choices=[('som', 'som'), ('₽', '₽'), ('$', '$')], default='som', max_length=10),
        ),
    ]
